from django.db import models
from django.contrib.postgres.fields import JSONField

class Dell(models.Model):
    ID = models.IntegerField(primary_key=True)
    LaptopName = models.CharField(max_length = 50)
    photo = models.CharField(max_length=1000)
    ScreenSize = models.FloatField(null=True, blank=True, default=None)
    RAM = models.IntegerField()
    Cost = models.IntegerField()
    Color = models.CharField(max_length=50)
    GraphicCard = models.CharField(max_length=50)
    Gcompany = models.CharField(max_length=50)
    Memory = models.CharField(max_length=50)
    Processor = models.CharField(max_length=50)
    Rating = models.FloatField(null=True, blank=True, default=None)
    Accessories = models.CharField(max_length=50)
class accessories(models.Model):
    ID = models.IntegerField(primary_key=True)
    Name = models.CharField(max_length = 50)
    photo = models.CharField(max_length=1000)
    Cost = models.IntegerField()
class history(models.Model):
    customerID =models.AutoField(primary_key=True)
    history = JSONField()
class BackendAnalytics(models.Model):
    customerID = models.AutoField(primary_key=True)
    PscreenSize = models.FloatField(null=True, blank=True, default=None)
    PRAM = models.IntegerField()
    PCost = models.IntegerField()
    PColor = models.CharField(max_length=50)
    PGraphicCard = models.IntegerField()
    PGcompany = models.CharField(max_length=50)
    PMemory = models.CharField(max_length=50)
    PProcessor = models.CharField(max_length=50)
    RscreenSize = models.FloatField(null=True, blank=True, default=None)
    RRAM = models.IntegerField()
    RCost = models.IntegerField()
    RColor = models.CharField(max_length=50)
    RGraphicCard = models.IntegerField()
    RGcompany = models.CharField(max_length=50)
    RMemory = models.CharField(max_length=50)
    RProcessor = models.CharField(max_length=50)
    comment = models.CharField(max_length=300)
    selectedID = models.IntegerField()
