# Generated by Django 2.2.5 on 2019-10-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=1000)),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BackendAnalytics',
            fields=[
                ('customerID', models.IntegerField(primary_key=True, serialize=False)),
                ('PscreenSize', models.FloatField(blank=True, default=None, null=True)),
                ('PRAM', models.IntegerField()),
                ('PCost', models.IntegerField()),
                ('PColor', models.CharField(max_length=50)),
                ('PGraphicCard', models.IntegerField()),
                ('PGcompany', models.CharField(max_length=50)),
                ('PMemory', models.CharField(max_length=50)),
                ('PProcessor', models.CharField(max_length=50)),
                ('RscreenSize', models.FloatField(blank=True, default=None, null=True)),
                ('RRAM', models.IntegerField()),
                ('RCost', models.IntegerField()),
                ('RColor', models.CharField(max_length=50)),
                ('RGraphicCard', models.IntegerField()),
                ('RGcompany', models.CharField(max_length=50)),
                ('RMemory', models.CharField(max_length=50)),
                ('RProcessor', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=300)),
                ('selectedID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('laptopName', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=1000)),
                ('screenSize', models.FloatField(blank=True, default=None, null=True)),
                ('RAM', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('Color', models.CharField(max_length=50)),
                ('GraphicCard', models.IntegerField()),
                ('Gcompany', models.CharField(max_length=50)),
                ('Memory', models.CharField(max_length=50)),
                ('Processor', models.CharField(max_length=50)),
                ('Rating', models.IntegerField()),
                ('Accessories', models.CharField(max_length=50)),
            ],
        ),
    ]
