# Generated by Django 2.2.5 on 2019-10-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='dell',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='dell',
            old_name='laptopName',
            new_name='LaptopName',
        ),
        migrations.RenameField(
            model_name='dell',
            old_name='screenSize',
            new_name='ScreenSize',
        ),
        migrations.AlterField(
            model_name='dell',
            name='Rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
