# Generated by Django 2.2.5 on 2019-10-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dell', '0002_auto_20191019_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dell',
            name='GraphicCard',
            field=models.CharField(max_length=50),
        ),
    ]
