# Generated by Django 2.2.5 on 2019-10-21 16:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dell', '0003_auto_20191019_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('customerID', models.IntegerField(primary_key=True, serialize=False)),
                ('history', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
